#! /usr/bin/python3

invalid = '0x80'

print()
print("#ifndef __B64_LOOKUP__")
print("#define __B64_LOOKUP__")
print()
print("#include <stdint.h>")
print()

print("#define INV_VAL " + invalid)
print()
print("const char g_B64[0x80] = ")
print("{")

for i in range(0, ord('+')):
        print(invalid + ',')

# +
print("62,")

for i in range(1, ord('/') - ord('+')):
    print(invalid + ',')

# /
print("63,")

# 0 - 9
for i in range(52, 62):
    print(str(i) + ",")

for i in range (1, ord('A') - ord('9')):
    print(invalid + ',')

# A - Z
for i in range(0, 26):
    print(str(i) + ',')

for i in range(1, ord('a') - ord('Z')):
    print(invalid + ',')

# a - z
for i in range(26, 52):
    print(str(i) + ',')

for i in range(1, 0x7e - ord('z')):
    print(invalid + ',')

print(invalid)
print("};")
print()
print("#endif")
print()

