#! /usr/bin/python3

invalid = '0xff'

def printInvalidRange(start, end):
    for i in range(start,end):
        print(invalid + ',')

print()
print("#ifndef __HEX_LOOKUP__")
print("#define __HEX_LOOKUP__")
print()
print("#include <stdint.h>")
print()

print("#define INVALID_SYMBOL " + invalid)
print()
print("const uint8_t g_Hex[0x80] = ")
print("{")

printInvalidRange(0, ord('0'))

for i in range(0, 10):
    print(str(i) + ",")

printInvalidRange(ord('9')+1, ord('A'))

print("0x0a,")
print("0x0b,")
print("0x0c,")
print("0x0d,")
print("0x0e,")
print("0x0f,")

printInvalidRange(ord('F')+1, ord('a'))

print("0x0a,")
print("0x0b,")
print("0x0c,")
print("0x0d,")
print("0x0e,")
print("0x0f,")

printInvalidRange(ord('f')+1, 0x7f)

print(invalid)
print("};")
print()
print("#endif")
print()

