
#ifndef _HEX_LOOKUP_
#define _HEX_LOOKUP_

#include <stdint.h>

#define INV_SYM 0xff

const uint8_t g_Hex[0x80] = 
{
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    0,      1,      2,      3,      4,      5,      6,      7,
    8,      9,      INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,0x0a,   0x0b,   0x0c,   0x0d,   0x0e,   0x0f,   INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,0x0a,   0x0b,   0x0c,   0x0d,   0x0e,   0x0f,   INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,
    INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM,INV_SYM
};

#endif

