#! /usr/bin/python3

import random
import sys

charset = ['0','1','2','3','4','5','6','7','8','9','a',
               'b','c','d','e','f','A','B','C','D','E','F']

if len(sys.argv) < 2:
    raise Exception("argv[1] must be present as the count of nybbles to generate")

for _ in range(0, int(sys.argv[1])):
    print(random.choice(charset), end='')

